### PR TITLE
Added Kosovo as a country

### PR DESCRIPTION
**Pull request by alanj1998**

### CODE REVIEW

**Comment by ShaneMcGowan** [comment]
@alanj1998 The country was not added in alphabetical order, can you please fix this? I can't merge this into master until it is fixed as it violates our code of conduct not to adhere to strict alphabetical ordering

**Comment by alanj1998** [comment]
Sorry I cannot accept this as a change request as it does not follow the Pull Request Update Template specified on Github's main page. Please rephrase your request to match the Template.

**Comment by ShaneMcGowan** [comment]
@alanj1998 I have since updated the repository with a pull request template, apologies for any inconvenience

**Comment by alanj1998** [comment]
Closing due to lack of information on Kosovo.

**Pull request closed without merging**
